name = "nextjs-cloudflare"
compatibility_date = "2024-06-30"
pages_build_output_dir = ".output"

# KV namespace binding for Pages Functions if deploying from command line
# [[kv_namespaces]]
# binding = "kv_store"
# id = ""
# preview_id = "" 