name = "nextjs-cloudflare"
compatibility_date = "2024-06-30"

# This config is for Cloudflare Pages (not Workers)
# KV namespace binding for Pages Functions
[[kv_namespaces]]
binding = "kv_store"
id = ""
preview_id = "" 